project_id = "axtopbwmwmajrrujqoza"

[functions.create-payment]
verify_jwt = false

[functions.process-payment-success]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.ia-recommendations]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false