import { SpaceProps } from '@/components/ui-custom/SpaceCard';
import { supabase } from '@/integrations/supabase/client';
import { parkingImages, getRandomParkingImages } from '@/assets/parking';

// Função para calcular distância entre dois pontos usando a fórmula de Haversine
function calculateDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371; // Raio da Terra em km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
    Math.sin(dLng/2) * Math.sin(dLng/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  const distance = R * c;
  return distance;
}

// Função para formatar distância
function formatDistance(distance: number): string {
  if (distance < 1) {
    return `${Math.round(distance * 1000)}m`;
  }
  return `${distance.toFixed(1)}km`;
}

// Helper function to convert Supabase data to SpaceProps format
function convertSupabaseToSpaceProps(vagaDB: any): SpaceProps {
  return {
    id: vagaDB.id,
    title: vagaDB.titulo || 'Vaga sem título',
    address: vagaDB.endereco || 'Endereço não informado',
    price: vagaDB.preco_hora || vagaDB.price || 0,
    priceHour: vagaDB.preco_hora || vagaDB.price || 0,
    priceDay: vagaDB.preco_dia || null,
    rating: vagaDB.rating || 4.0,
    reviewCount: Math.floor(Math.random() * 100) + 20, // Generate random review count
    description: `Vaga localizada em ${vagaDB.endereco || 'localização privilegiada'}. ${vagaDB.recursos?.length > 0 ? 'Conta com ' + vagaDB.recursos.join(', ') + '.' : ''} Disponível 24 horas por dia com segurança garantida.`,
    features: vagaDB.recursos || vagaDB.features || [],
    imageUrl: (vagaDB.image_url && !vagaDB.image_url.includes('unsplash.com') && !vagaDB.image_url.includes('images.unsplash.com') && !vagaDB.image_url.includes('pexels.com') && !vagaDB.image_url.includes('picsum.photos') && !vagaDB.image_url.includes('placeholder') ? vagaDB.image_url : parkingImages[0]),
    rules: [
      'Check-in a partir das 6h00',
      'Check-out até às 22h00',
      'Apresente o QR code na entrada',
      'Mantenha a vaga sempre limpa',
    ],
    owner: {
      name: 'Proprietário Verificado',
      joined: 'Janeiro de 2023',
      responseTime: '30 min',
      rating: 4.8,
        image: parkingImages[5],
    },
    images: [
      (vagaDB.image_url && !vagaDB.image_url.includes('unsplash.com') && !vagaDB.image_url.includes('images.unsplash.com') && !vagaDB.image_url.includes('pexels.com') && !vagaDB.image_url.includes('picsum.photos') && !vagaDB.image_url.includes('placeholder') ? vagaDB.image_url : parkingImages[0]),
      ...getRandomParkingImages(4).filter(img => img !== (vagaDB.image_url && !vagaDB.image_url.includes('unsplash.com') && !vagaDB.image_url.includes('images.unsplash.com') && !vagaDB.image_url.includes('pexels.com') && !vagaDB.image_url.includes('picsum.photos') && !vagaDB.image_url.includes('placeholder') ? vagaDB.image_url : parkingImages[0])),
    ],
    reviews: [
      {
        id: '1',
        user: 'Cliente Satisfeito',
        date: '15/08/2024',
        rating: 5,
        comment: 'Excelente localização e fácil acesso. Recomendo!',
          image: parkingImages[6],
      },
      {
        id: '2',
        user: 'Usuário Frequente',
        date: '10/08/2024',
        rating: 4,
        comment: 'Boa opção para estacionar com segurança.',
          image: parkingImages[7],
      },
    ],
    lat: vagaDB.lat || -23.5505,
    lng: vagaDB.lng || -46.6333,
    location: {
      lat: vagaDB.lat || -23.5505,
      lng: vagaDB.lng || -46.6333,
      nearbyPlaces: ['Centro Comercial (200m)', 'Transporte público (150m)', 'Farmácia (100m)'],
    },
    availability: {
      monday: '06:00 - 22:00',
      tuesday: '06:00 - 22:00',
      wednesday: '06:00 - 22:00',
      thursday: '06:00 - 22:00',
      friday: '06:00 - 22:00',
      saturday: '08:00 - 20:00',
      sunday: '08:00 - 18:00',
    },
    type: vagaDB.bairro || 'Médio',
    available: vagaDB.available !== false,
    distance: '350m',
    discount_premium: vagaDB.discount_premium || false,
  };
}

export async function fetchSpace(id: string): Promise<SpaceProps> {
  console.log('Fetching space with ID:', id);
  
  // Simulate loading delay
  await new Promise(resolve => setTimeout(resolve, 800));
  
  try {
    // First, try to fetch from Supabase
    const { data: vagaFromDB, error } = await supabase
      .from('vagas')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (!error && vagaFromDB) {
      console.log('✅ Vaga encontrada no Supabase:', vagaFromDB);
      return convertSupabaseToSpaceProps(vagaFromDB);
    } else {
      console.log('❌ Vaga não encontrada no Supabase para ID:', id, 'Error:', error);
    }
  } catch (error) {
    console.error('Erro ao buscar vaga no Supabase:', error);
  }

  console.log('📦 Fallback para dados mock para ID:', id);
  // Fallback to mock data if not found in Supabase
  const mockSpaces: Record<string, SpaceProps> = {
    '1': {
      id: '1',
      title: 'Estacionamento Seguro na Paulista',
      address: 'Av. Paulista, 1000 - São Paulo, SP',
      price: 15,
      priceHour: 15,
      priceDay: 90,
      rating: 4.8,
      reviewCount: 125,
      description: 'Vaga coberta e segura em estacionamento privativo. Localizada próxima à estação Trianon-Masp do metrô. Segurança 24h, câmeras de monitoramento e seguro incluso.',
      features: ['Coberto', 'Segurança 24h', 'Seguro', 'Carregador EV', 'Lavagem'],
      imageUrl: parkingImages[0],
      rules: [
        'Check-in a partir das 6h00',
        'Check-out até às 22h00',
        'Não é permitido pernoitar',
        'Apresente o QR code na entrada',
      ],
      owner: {
        name: 'Carlos Silva',
        joined: 'Março de 2022',
        responseTime: '15 min',
        rating: 4.9,
        image: parkingImages[8],
      },
      images: [
        parkingImages[0],
        parkingImages[1],
        parkingImages[2],
        parkingImages[3],
        parkingImages[4],
      ],
      reviews: [
        {
          id: '1',
          user: 'Marina Costa',
          date: '12/04/2023',
          rating: 5,
          comment: 'Ótima localização e muito fácil de acessar. Estacionamento seguro e limpo.',
          image: parkingImages[9],
        },
        {
          id: '2',
          user: 'Pedro Gomes',
          date: '29/03/2023',
          rating: 4,
          comment: 'Bom espaço e segurança, porém o acesso poderia ser mais rápido.',
          image: parkingImages[10],
        },
      ],
      lat: -23.5629,
      lng: -46.6544,
      location: {
        lat: -23.5629,
        lng: -46.6544,
        nearbyPlaces: ['Estação Trianon-Masp (350m)', 'MASP (400m)', 'Parque Trianon (450m)'],
      },
      availability: {
        monday: '06:00 - 22:00',
        tuesday: '06:00 - 22:00',
        wednesday: '06:00 - 22:00',
        thursday: '06:00 - 22:00',
        friday: '06:00 - 22:00',
        saturday: '08:00 - 20:00',
        sunday: '08:00 - 18:00',
      },
      type: 'Médio',
      available: true,
      distance: '300m',
    },
    '2': {
      id: '2',
      title: 'Vaga Residencial em Pinheiros',
      address: 'R. dos Pinheiros, 275 - São Paulo',
      price: 10,
      priceHour: 10,
      priceDay: 60,
      rating: 4.5,
      reviewCount: 87,
      description: 'Vaga residencial bem localizada no bairro de Pinheiros. Acesso fácil, ambiente seguro e monitorado por câmeras.',
      features: ['Privativo', 'Coberto', 'Segurança'],
      imageUrl: parkingImages[1],
      images: [
        parkingImages[5],
        parkingImages[6],
        parkingImages[7],
        parkingImages[8],
        parkingImages[9],
      ],
      lat: -23.5651,
      lng: -46.6911,
      location: {
        lat: -23.5651,
        lng: -46.6911,
        nearbyPlaces: ['Estação Faria Lima (450m)', 'Shopping Pátio Higienópolis (800m)'],
      },
      reviews: [
        {
          id: '1',
          user: 'João Silva',
          date: '01/03/2023',
          rating: 5,
          comment: 'Excelente localização, fácil acesso.',
          image: parkingImages[11],
        },
      ],
      owner: {
        name: 'Ana Martins',
        joined: 'Janeiro de 2023',
        responseTime: '30 min',
        rating: 4.7,
        image: parkingImages[12],
      },
      rules: ['Check-in flexível', 'Aviso prévio de 1h para reservas'],
      availability: {
        monday: '07:00 - 22:00',
        tuesday: '07:00 - 22:00',
        wednesday: '07:00 - 22:00',
        thursday: '07:00 - 22:00',
        friday: '07:00 - 22:00',
        saturday: '09:00 - 18:00',
        sunday: '10:00 - 16:00',
      },
      type: 'Pequeno',
      available: true,
      distance: '1.2km',
    },
    '3': {
      id: '3',
      title: 'Estacionamento 24h Centro',
      address: 'R. 7 de Abril, 154 - São Paulo',
      price: 12,
      priceHour: 12,
      priceDay: 70,
      rating: 4.2,
      reviewCount: 63,
      description: 'Estacionamento no centro de São Paulo, aberto 24 horas. Equipe de segurança presente e monitoramento por câmeras.',
      features: ['24h', 'Segurança', 'Coberto'],
      imageUrl: parkingImages[2],
      images: [
        parkingImages[10],
        parkingImages[11],
        parkingImages[12],
        parkingImages[13],
        parkingImages[14],
      ],
      lat: -23.5469,
      lng: -46.6389,
      type: 'Médio',
      available: true,
      distance: '2.5km',
    },
    '4': {
      id: '4',
      title: 'Vaga Coberta Vila Madalena',
      address: 'R. Fradique Coutinho, 320 - São Paulo',
      price: 18,
      priceHour: 18,
      priceDay: 100,
      rating: 4.7,
      reviewCount: 42,
      description: 'Vaga premium em condomínio fechado na Vila Madalena. Espaço amplo, ideal para SUVs. Próximo a bares e restaurantes.',
      features: ['Coberto', 'Privativo', 'Lavagem'],
      imageUrl: parkingImages[3],
      images: [
        parkingImages[15],
        parkingImages[0],
        parkingImages[1],
        parkingImages[2],
        parkingImages[3],
      ],
      lat: -23.5557,
      lng: -46.6859,
      type: 'SUV',
      available: true,
      distance: '3.1km',
    },
    '5': {
      id: '5',
      title: 'Estacionamento Shopping Ibirapuera',
      address: 'Av. Ibirapuera, 3103 - São Paulo',
      price: 15,
      priceHour: 15,
      priceDay: 85,
      rating: 4.4,
      reviewCount: 128,
      description: 'Vagas cobertas próximas ao Shopping Ibirapuera. Segurança 24h e fácil acesso.',
      features: ['Shopping', 'Coberto', 'Segurança 24h'],
      imageUrl: parkingImages[4],
      images: [
        parkingImages[4],
        parkingImages[5],
        parkingImages[6],
        parkingImages[7],
        parkingImages[8],
      ],
      lat: -23.6081,
      lng: -46.6676,
      type: 'Médio',
      available: true,
      distance: '4.2km',
    },
    '6': {
      id: '6',
      title: 'Vaga Privativa Jardins',
      address: 'R. Oscar Freire, 725 - São Paulo',
      price: 25,
      priceHour: 25,
      priceDay: 150,
      rating: 4.9,
      reviewCount: 36,
      description: 'Vaga exclusiva em prédio de alto padrão nos Jardins. Acesso controlado, monitoramento 24h.',
      features: ['Premium', 'Segurança', 'Câmeras'],
      imageUrl: parkingImages[5],
      images: [
        parkingImages[5],
        parkingImages[6],
      ],
      lat: -23.5623,
      lng: -46.6691,
      type: 'Pequeno',
      available: true,
      distance: '2.8km',
    },
    '7': {
      id: '7',
      title: 'Estacionamento Aeroporto Congonhas',
      address: 'Av. Washington Luís, s/n - São Paulo',
      price: 20,
      priceHour: 20,
      priceDay: 120,
      rating: 4.3,
      reviewCount: 215,
      description: 'Estacionamento próximo ao Aeroporto de Congonhas. Ideal para viagens curtas ou longas.',
      features: ['Aeroporto', 'Segurança', '24h'],
      imageUrl: parkingImages[6],
      images: [
        parkingImages[6],
        parkingImages[7],
      ],
      lat: -23.6267,
      lng: -46.6559,
      type: 'Médio',
      available: true,
      distance: '7.5km',
    },
    '8': {
      id: '8',
      title: 'Vaga Rua Vergueiro',
      address: 'R. Vergueiro, 1421 - São Paulo',
      price: 10,
      priceHour: 10,
      priceDay: 60,
      rating: 4.1,
      reviewCount: 52,
      description: 'Vaga em edifício residencial na Rua Vergueiro. Próximo ao metrô Paraíso.',
      features: ['Residencial', 'Metrô', 'Coberto'],
      imageUrl: parkingImages[7],
      images: [
        parkingImages[7],
        parkingImages[8],
      ],
      lat: -23.5725,
      lng: -46.6382,
      type: 'Pequeno',
      available: true,
      distance: '3.8km',
    },
    '9': {
      id: '9',
      title: 'Estacionamento Shopping Morumbi',
      address: 'Av. Roque Petroni Júnior, 1089 - São Paulo',
      price: 14,
      priceHour: 14,
      priceDay: 80,
      rating: 4.5,
      reviewCount: 167,
      description: 'Vagas amplas próximas ao Shopping Morumbi. Excelente para compras.',
      features: ['Shopping', 'Segurança', 'Coberto'],
      imageUrl: parkingImages[8],
      images: [
        parkingImages[8],
        parkingImages[9],
      ],
      lat: -23.6228,
      lng: -46.7016,
      type: 'Médio',
      available: true,
      distance: '8.3km',
    },
    '10': {
      id: '10',
      title: 'Vaga Residencial Itaim Bibi',
      address: 'R. João Cachoeira, 512 - São Paulo',
      price: 22,
      priceHour: 22,
      priceDay: 130,
      rating: 4.8,
      reviewCount: 47,
      description: 'Vaga em condomínio fechado no Itaim Bibi. Segurança 24h e fácil acesso.',
      features: ['Privativo', 'Condomínio', 'Segurança'],
      imageUrl: parkingImages[9],
      images: [
        parkingImages[9],
        parkingImages[10],
      ],
      lat: -23.5828,
      lng: -46.6764,
      type: 'SUV',
      available: false,
      distance: '4.7km',
    },
    '11': {
      id: '11',
      title: 'Estacionamento Hospital Albert Einstein',
      address: 'Av. Albert Einstein, 627 - São Paulo',
      price: 18,
      priceHour: 18,
      priceDay: 100,
      rating: 4.2,
      reviewCount: 89,
      description: 'Vagas de fácil acesso próximas ao Hospital Albert Einstein. Ideal para visitas médicas.',
      features: ['Hospital', '24h', 'Coberto'],
      imageUrl: parkingImages[10],
      images: [
        parkingImages[10],
        parkingImages[11],
      ],
      lat: -23.5999,
      lng: -46.7151,
      type: 'Médio',
      available: true,
      distance: '7.9km',
    },
    '12': {
      id: '12',
      title: 'Vaga Privativa Perdizes',
      address: 'R. Bartira, 351 - São Paulo',
      price: 15,
      priceHour: 15,
      priceDay: 85,
      rating: 4.6,
      reviewCount: 38,
      description: 'Vaga em condomínio residencial nas Perdizes. Ambiente seguro e tranquilo.',
      features: ['Residencial', 'Privativo', 'Segurança'],
      imageUrl: parkingImages[11],
      images: [
        parkingImages[11],
        parkingImages[12],
      ],
      lat: -23.5373,
      lng: -46.6784,
      type: 'Pequeno',
      available: true,
      distance: '5.1km',
    },
    '13': {
      id: '13',
      title: 'Estacionamento UNINOVE',
      address: 'R. Vergueiro, 235 - São Paulo',
      price: 8,
      priceHour: 8,
      priceDay: 45,
      rating: 3.9,
      reviewCount: 112,
      description: 'Estacionamento próximo à Universidade Nove de Julho. Ideal para estudantes.',
      features: ['Universidade', 'Econômico'],
      imageUrl: parkingImages[12],
      images: [
        parkingImages[12],
        parkingImages[13],
      ],
      lat: -23.5515,
      lng: -46.6401,
      type: 'Pequeno',
      available: true,
      distance: '1.8km',
    },
    '14': {
      id: '14',
      title: 'Vaga Shopping Eldorado',
      address: 'Av. Rebouças, 3970 - São Paulo',
      price: 15,
      priceHour: 15,
      priceDay: 85,
      rating: 4.4,
      reviewCount: 143,
      description: 'Estacionamento fácil e seguro no Shopping Eldorado. Ideal para compras e lazer.',
      features: ['Shopping', 'Coberto', 'Segurança'],
      imageUrl: parkingImages[13],
      images: [
        parkingImages[13],
        parkingImages[14],
      ],
      lat: -23.5744,
      lng: -46.7013,
      type: 'Médio',
      available: true,
      distance: '6.2km',
    },
    '15': {
      id: '15',
      title: 'Estacionamento Centro Cultural São Paulo',
      address: 'R. Vergueiro, 1000 - São Paulo',
      price: 12,
      priceHour: 12,
      priceDay: 70,
      rating: 4.3,
      reviewCount: 76,
      description: 'Vagas próximas ao Centro Cultural São Paulo. Ideal para eventos culturais.',
      features: ['Cultural', 'Metrô', 'Coberto'],
      imageUrl: parkingImages[14],
      images: [
        parkingImages[14],
        parkingImages[15],
      ],
      lat: -23.5717,
      lng: -46.6395,
      type: 'Pequeno',
      available: true,
      distance: '2.9km',
    },
    '16': {
      id: '16',
      title: 'Vaga Edifício Copan',
      address: 'Av. Ipiranga, 200 - São Paulo',
      price: 16,
      priceHour: 16,
      priceDay: 95,
      rating: 4.4,
      reviewCount: 58,
      description: 'Vaga no icônico Edifício Copan, no centro de São Paulo. Ótima localização.',
      features: ['Centro', 'Histórico', 'Segurança'],
      imageUrl: parkingImages[15],
      images: [
        parkingImages[15],
        parkingImages[16],
      ],
      lat: -23.5469,
      lng: -46.6451,
      type: 'Médio',
      available: false,
      distance: '1.5km',
    },
    '17': {
      id: '17',
      title: 'Estacionamento Estação Sé',
      address: 'Praça da Sé - São Paulo',
      price: 10,
      priceHour: 10,
      priceDay: 60,
      rating: 4.0,
      reviewCount: 195,
      description: 'Estacionamento próximo à Estação Sé do Metrô. Localização central.',
      features: ['Metrô', 'Centro', 'Econômico'],
      imageUrl: parkingImages[16],
      images: [
        parkingImages[16],
        parkingImages[17],
      ],
      lat: -23.5504,
      lng: -46.6333,
      type: 'Pequeno',
      available: true,
      distance: '1.0km',
    },
    '18': {
      id: '18',
      title: 'Vaga USP',
      address: 'Av. Prof. Luciano Gualberto, 315 - São Paulo',
      price: 8,
      priceHour: 8,
      priceDay: 45,
      rating: 4.1,
      reviewCount: 87,
      description: 'Vaga próxima à Universidade de São Paulo. Ideal para estudantes e professores.',
      features: ['Universidade', 'Econômico'],
      imageUrl: parkingImages[17],
      images: [
        parkingImages[17],
        parkingImages[18],
      ],
      lat: -23.5599,
      lng: -46.7308,
      type: 'Pequeno',
      available: true,
      distance: '9.5km',
    },
    '19': {
      id: '19',
      title: 'Estacionamento Parque Ibirapuera',
      address: 'Av. Pedro Álvares Cabral - São Paulo',
      price: 12,
      priceHour: 12,
      priceDay: 65,
      rating: 4.6,
      reviewCount: 225,
      description: 'Vagas próximas ao Parque Ibirapuera. Ideal para lazer e atividades ao ar livre.',
      features: ['Parque', 'Lazer', 'Segurança'],
      imageUrl: parkingImages[18],
      images: [
        parkingImages[18],
        parkingImages[19],
      ],
      lat: -23.5874,
      lng: -46.6576,
      type: 'Médio',
      available: true,
      distance: '5.4km',
    },
    '20': {
      id: '20',
      title: 'Vaga Terminal Tietê',
      address: 'Av. Cruzeiro do Sul, 1800 - São Paulo',
      price: 14,
      priceHour: 14,
      priceDay: 80,
      rating: 4.2,
      reviewCount: 178,
      description: 'Estacionamento próximo ao Terminal Tietê. Ideal para viagens de ônibus.',
      features: ['Terminal', '24h', 'Segurança'],
      imageUrl: parkingImages[19],
      images: [
        parkingImages[19],
        parkingImages[20],
      ],
      lat: -23.5162,
      lng: -46.6252,
      type: 'Médio',
      available: true,
      distance: '6.8km',
    },
    '21': {
      id: '21',
      title: 'Estacionamento Shopping Tatuapé',
      address: 'R. Domingos Agostim, 91 - São Paulo',
      price: 13,
      priceHour: 13,
      priceDay: 75,
      rating: 4.3,
      reviewCount: 156,
      description: 'Vagas amplas no Shopping Tatuapé. Ideal para compras e lazer na zona leste.',
      features: ['Shopping', 'Coberto', 'Segurança'],
      imageUrl: parkingImages[20],
      images: [
        parkingImages[20],
        parkingImages[21],
      ],
      lat: -23.5376,
      lng: -46.5763,
      type: 'Médio',
      available: true,
      distance: '8.2km',
    },
    '22': {
      id: '22',
      title: 'Vaga Privativa Santana',
      address: 'R. Dr. César, 530 - São Paulo',
      price: 11,
      priceHour: 11,
      priceDay: 65,
      rating: 4.4,
      reviewCount: 42,
      description: 'Vaga em condomínio residencial em Santana. Acesso fácil e seguro.',
      features: ['Residencial', 'Privativo', 'Portaria'],
      imageUrl: parkingImages[0],
      images: [
        parkingImages[0],
        parkingImages[1],
      ],
      lat: -23.5045,
      lng: -46.6361,
      type: 'Pequeno',
      available: true,
      distance: '7.1km',
    },
    '23': {
      id: '23',
      title: 'Estacionamento Mercado Municipal',
      address: 'R. da Cantareira, 306 - São Paulo',
      price: 12,
      priceHour: 12,
      priceDay: 70,
      rating: 4.0,
      reviewCount: 132,
      description: 'Estacionamento próximo ao Mercado Municipal de São Paulo. Ideal para visitas gastronômicas.',
      features: ['Centro', 'Turístico', 'Segurança'],
      imageUrl: parkingImages[1],
      images: [
        parkingImages[1],
        parkingImages[2],
      ],
      lat: -23.5418,
      lng: -46.6294,
      type: 'Médio',
      available: true,
      distance: '2.2km',
    },
    '24': {
      id: '24',
      title: 'Vaga Teatro Municipal',
      address: 'Praça Ramos de Azevedo - São Paulo',
      price: 20,
      priceHour: 20,
      priceDay: 120,
      rating: 4.7,
      reviewCount: 65,
      description: 'Vaga exclusiva próxima ao Teatro Municipal. Ideal para eventos culturais no centro.',
      features: ['Cultural', 'Centro', 'VIP'],
      imageUrl: parkingImages[2],
      images: [
        parkingImages[2],
        parkingImages[3],
      ],
      lat: -23.5453,
      lng: -46.6388,
      type: 'SUV',
      available: true,
      distance: '1.7km',
    },
    '25': {
      id: '25',
      title: 'Garagem Privativa Paulista Executive',
      address: 'Av. Paulista, 854 - São Paulo, SP',
      price: 18,
      priceHour: 18,
      priceDay: 105,
      rating: 4.8,
      reviewCount: 142,
      description: 'Garagem coberta em edifício comercial de alto padrão na Av. Paulista. Segurança 24h, sistema automatizado e localização privilegiada.',
      features: ['Coberto', 'Segurança 24h', 'Automatizado', 'Executivo', 'Câmeras'],
      imageUrl: parkingImages[3],
      rules: ['Check-in 24h', 'Acesso por cartão', 'Altura máxima 2.10m', 'Seguro obrigatório'],
      owner: {
        name: 'Roberto Mendes',
        joined: 'Janeiro de 2021',
        responseTime: '5 min',
        rating: 4.9,
        image: parkingImages[4],
      },
      images: [parkingImages[3], parkingImages[4], parkingImages[5], parkingImages[6]],
      reviews: [
        {
          id: '25a',
          user: 'Ana Paula Silva',
          date: '15/03/2024',
          rating: 5,
          comment: 'Excelente localização e garagem muito bem cuidada. Recomendo!',
          image: parkingImages[7],
        },
        {
          id: '25b',
          user: 'João Santos',
          date: '08/03/2024',
          rating: 5,
          comment: 'Perfeito para trabalhar na Paulista. Acesso fácil e seguro.',
          image: parkingImages[8],
        },
      ],
      lat: -23.5650,
      lng: -46.6553,
      location: {
        lat: -23.5650,
        lng: -46.6553,
        nearbyPlaces: ['Estação Brigadeiro (200m)', 'FIESP (150m)', 'Shopping Center 3 (300m)'],
      },
      availability: {
        monday: '00:00 - 23:59',
        tuesday: '00:00 - 23:59',
        wednesday: '00:00 - 23:59',
        thursday: '00:00 - 23:59',
        friday: '00:00 - 23:59',
        saturday: '00:00 - 23:59',
        sunday: '00:00 - 23:59',
      },
      type: 'Médio',
      available: true,
      distance: '250m',
    },
    '26': {
      id: '26',
      title: 'Estacionamento Subsolo Augusta',
      address: 'R. Augusta, 2532 - São Paulo, SP',
      price: 14,
      priceHour: 14,
      priceDay: 85,
      rating: 4.6,
      reviewCount: 98,
      description: 'Garagem subterrânea moderna com ventilação adequada. Próximo à Augusta e Paulista, ideal para lazer e trabalho.',
      features: ['Subsolo', 'Ventilado', 'Moderno', 'Lazer', '24h'],
      imageUrl: parkingImages[5],
      rules: ['Acesso 24h', 'Máximo 48h consecutivas', 'Proibido lavagem', 'Seguro incluso'],
      owner: {
        name: 'Mariana Costa',
        joined: 'Setembro de 2020',
        responseTime: '12 min',
        rating: 4.7,
        image: parkingImages[9],
      },
      images: [parkingImages[5], parkingImages[10], parkingImages[11], parkingImages[12]],
      reviews: [
        {
          id: '26a',
          user: 'Carlos Eduardo',
          date: '22/03/2024',
          rating: 5,
          comment: 'Garagem ampla e bem iluminada. Preço justo para a região.',
          image: parkingImages[13],
        },
        {
          id: '26b',
          user: 'Patricia Lima',
          date: '18/03/2024',
          rating: 4,
          comment: 'Boa localização, mas às vezes fica cheio nos fins de semana.',
          image: parkingImages[14],
        },
      ],
      lat: -23.5587,
      lng: -46.6632,
      location: {
        lat: -23.5587,
        lng: -46.6632,
        nearbyPlaces: ['Rua Augusta (100m)', 'Estação Consolação (400m)', 'Roosevelt Square (350m)'],
      },
      availability: {
        monday: '00:00 - 23:59',
        tuesday: '00:00 - 23:59',
        wednesday: '00:00 - 23:59',
        thursday: '00:00 - 23:59',
        friday: '00:00 - 23:59',
        saturday: '00:00 - 23:59',
        sunday: '00:00 - 23:59',
      },
      type: 'Médio',
      available: true,
      distance: '400m',
    },
    '27': {
      id: '27',
      title: 'Garagem Conjunto Nacional',
      address: 'Av. Paulista, 2073 - São Paulo, SP',
      price: 16,
      priceHour: 16,
      priceDay: 95,
      rating: 4.7,
      reviewCount: 203,
      description: 'Estacionamento no icônico Conjunto Nacional. Localização central na Paulista com acesso direto ao shopping.',
      features: ['Shopping', 'Centro', 'Histórico', 'Coberto', 'Elevador'],
      imageUrl: parkingImages[6],
      rules: ['Horário comercial', 'Validação no shopping', 'Altura até 2.0m', 'Ticket obrigatório'],
      owner: {
        name: 'Administração CN',
        joined: 'Maio de 2019',
        responseTime: '20 min',
        rating: 4.8,
        image: parkingImages[15],
      },
      images: [parkingImages[6], parkingImages[16], parkingImages[17], parkingImages[18]],
      reviews: [
        {
          id: '27a',
          user: 'Fernanda Rodrigues',
          date: '25/03/2024',
          rating: 5,
          comment: 'Perfeito para fazer compras. Garagem organizada e limpa.',
          image: parkingImages[19],
        },
        {
          id: '27b',
          user: 'Marcos Paulo',
          date: '20/03/2024',
          rating: 4,
          comment: 'Boa localização, mas pode ficar congestionado na saída.',
          image: parkingImages[20],
        },
      ],
      lat: -23.5613,
      lng: -46.6563,
      location: {
        lat: -23.5613,
        lng: -46.6563,
        nearbyPlaces: ['Estação Trianon-Masp (50m)', 'MASP (200m)', 'Livraria Cultura (0m)'],
      },
      availability: {
        monday: '06:00 - 22:00',
        tuesday: '06:00 - 22:00',
        wednesday: '06:00 - 22:00',
        thursday: '06:00 - 22:00',
        friday: '06:00 - 22:00',
        saturday: '08:00 - 22:00',
        sunday: '10:00 - 20:00',
      },
      type: 'Médio',
      available: true,
      distance: '100m',
    },
    '28': {
      id: '28',
      title: 'Vaga Privativa Bela Vista Premium',
      address: 'R. Dr. Plínio Barreto, 285 - São Paulo, SP',
      price: 20,
      priceHour: 20,
      priceDay: 115,
      rating: 4.9,
      reviewCount: 87,
      description: 'Garagem premium em edifício residencial de luxo. Vaga demarcada, coberta e com serviços adicionais disponíveis.',
      features: ['Premium', 'Demarcada', 'Lavagem', 'Manobrista', 'VIP'],
      imageUrl: parkingImages[7],
      rules: ['Reserva antecipada', 'Serviço de manobrista', 'Lavagem opcional', 'Acesso restrito'],
      owner: {
        name: 'Eduardo Sampaio',
        joined: 'Dezembro de 2020',
        responseTime: '8 min',
        rating: 5.0,
        image: parkingImages[0],
      },
      images: [parkingImages[7], parkingImages[1], parkingImages[2], parkingImages[3]],
      reviews: [
        {
          id: '28a',
          user: 'Isabella Martins',
          date: '28/03/2024',
          rating: 5,
          comment: 'Serviço impecável! Meu carro sempre limpo e bem cuidado.',
          image: parkingImages[4],
        },
        {
          id: '28b',
          user: 'Rafael Oliveira',
          date: '24/03/2024',
          rating: 5,
          comment: 'Vale cada centavo. Tranquilidade total para trabalhar na região.',
          image: parkingImages[5],
        },
      ],
      lat: -23.5583,
      lng: -46.6547,
      location: {
        lat: -23.5583,
        lng: -46.6547,
        nearbyPlaces: ['Av. Paulista (150m)', 'Estação Brigadeiro (300m)', 'Casa das Rosas (250m)'],
      },
      availability: {
        monday: '06:00 - 22:00',
        tuesday: '06:00 - 22:00',
        wednesday: '06:00 - 22:00',
        thursday: '06:00 - 22:00',
        friday: '06:00 - 22:00',
        saturday: '08:00 - 20:00',
        sunday: '08:00 - 18:00',
      },
      type: 'SUV',
      available: true,
      distance: '180m',
    },
    '29': {
      id: '29',
      title: 'Estacionamento Rotativo Paulista Center',
      address: 'Av. Paulista, 1294 - São Paulo, SP',
      price: 12,
      priceHour: 12,
      priceDay: 72,
      rating: 4.4,
      reviewCount: 156,
      description: 'Estacionamento rotativo em prédio comercial. Ideal para reuniões de negócios e consultas médicas na região.',
      features: ['Rotativo', 'Comercial', 'Médico', 'Elevador', 'Recepção'],
      imageUrl: parkingImages[8],
      rules: ['Máximo 8h diárias', 'Comprovante obrigatório', 'Horário comercial', 'Validação na recepção'],
      owner: {
        name: 'Paulista Center Adm',
        joined: 'Março de 2022',
        responseTime: '15 min',
        rating: 4.5,
        image: parkingImages[6],
      },
      images: [parkingImages[8], parkingImages[9], parkingImages[10], parkingImages[11]],
      reviews: [
        {
          id: '29a',
          user: 'Dr. Henrique Silva',
          date: '30/03/2024',
          rating: 4,
          comment: 'Conveniente para consultas médicas. Localização excelente.',
          image: parkingImages[12],
        },
        {
          id: '29b',
          user: 'Claudia Santos',
          date: '26/03/2024',
          rating: 5,
          comment: 'Facilita muito para reuniões de trabalho na Paulista.',
          image: parkingImages[13],
        },
      ],
      lat: -23.5634,
      lng: -46.6589,
      location: {
        lat: -23.5634,
        lng: -46.6589,
        nearbyPlaces: ['Hospital Sírio Libanês (200m)', 'Estação Trianon-Masp (400m)', 'Shopping Center 3 (500m)'],
      },
      availability: {
        monday: '07:00 - 19:00',
        tuesday: '07:00 - 19:00',
        wednesday: '07:00 - 19:00',
        thursday: '07:00 - 19:00',
        friday: '07:00 - 19:00',
        saturday: '08:00 - 14:00',
        sunday: 'Fechado',
      },
      type: 'Pequeno',
      available: true,
      distance: '320m',
    },
    '30': {
      id: '30',
      title: 'Garagem Subsolo Paulista Plaza',
      address: 'Av. Paulista, 2064 - São Paulo, SP',
      price: 15,
      priceHour: 15,
      priceDay: 90,
      rating: 4.5,
      reviewCount: 134,
      description: 'Amplo estacionamento subterrâneo no Paulista Plaza. Moderno sistema de ventilação e iluminação LED.',
      features: ['Subsolo', 'Amplo', 'LED', 'Ventilação', 'Moderno'],
      imageUrl: parkingImages[9],
      rules: ['Acesso 24h', 'Cartão magnético', 'Seguro opcional', 'Lavagem permitida'],
      owner: {
        name: 'Plaza Administração',
        joined: 'Julho de 2021',
        responseTime: '10 min',
        rating: 4.6,
        image: parkingImages[14],
      },
      images: [parkingImages[9], parkingImages[15], parkingImages[16], parkingImages[17]],
      reviews: [
        {
          id: '30a',
          user: 'André Luiz',
          date: '02/04/2024',
          rating: 5,
          comment: 'Garagem moderna e bem sinalizada. Excelente custo-benefício.',
          image: parkingImages[18],
        },
        {
          id: '30b',
          user: 'Beatriz Almeida',
          date: '29/03/2024',
          rating: 4,
          comment: 'Boa opção na Paulista, mas às vezes demora para encontrar vaga.',
          image: parkingImages[19],
        },
      ],
      lat: -23.5612,
      lng: -46.6561,
      location: {
        lat: -23.5612,
        lng: -46.6561,
        nearbyPlaces: ['MASP (100m)', 'Parque Trianon (200m)', 'Casa das Rosas (300m)'],
      },
      availability: {
        monday: '00:00 - 23:59',
        tuesday: '00:00 - 23:59',
        wednesday: '00:00 - 23:59',
        thursday: '00:00 - 23:59',
        friday: '00:00 - 23:59',
        saturday: '00:00 - 23:59',
        sunday: '00:00 - 23:59',
      },
      type: 'Médio',
      available: true,
      distance: '120m',
    },
    '31': {
      id: '31',
      title: 'Vaga Corporativa Fiesp Tower',
      address: 'Av. Paulista, 1313 - São Paulo, SP',
      price: 22,
      priceHour: 22,
      priceDay: 130,
      rating: 4.8,
      reviewCount: 76,
      description: 'Estacionamento corporativo no edifício da FIESP. Ambiente executivo com serviços premium e segurança reforçada.',
      features: ['Corporativo', 'Executivo', 'Premium', 'Segurança++', 'Concierge'],
      imageUrl: parkingImages[10],
      rules: ['Acesso executivo', 'Identificação obrigatória', 'Dress code', 'Agendamento prévio'],
      owner: {
        name: 'FIESP Facilities',
        joined: 'Janeiro de 2020',
        responseTime: '5 min',
        rating: 4.9,
        image: parkingImages[20],
      },
      images: [parkingImages[10], parkingImages[0], parkingImages[1], parkingImages[2]],
      reviews: [
        {
          id: '31a',
          user: 'CEO Maria Helena',
          date: '05/04/2024',
          rating: 5,
          comment: 'Perfeito para reuniões executivas. Serviço impecável.',
          image: parkingImages[3],
        },
        {
          id: '31b',
          user: 'Diretor Paulo Cesar',
          date: '01/04/2024',
          rating: 5,
          comment: 'Ambiente corporativo de alto nível. Recomendo.',
          image: parkingImages[4],
        },
      ],
      lat: -23.5655,
      lng: -46.6555,
      location: {
        lat: -23.5655,
        lng: -46.6555,
        nearbyPlaces: ['FIESP (0m)', 'Estação Brigadeiro (150m)', 'Top Center (200m)'],
      },
      availability: {
        monday: '06:00 - 20:00',
        tuesday: '06:00 - 20:00',
        wednesday: '06:00 - 20:00',
        thursday: '06:00 - 20:00',
        friday: '06:00 - 20:00',
        saturday: '08:00 - 14:00',
        sunday: 'Fechado',
      },
      type: 'SUV',
      available: true,
      distance: '200m',
    },
    '32': {
      id: '32',
      title: 'Estacionamento Hospital Sírio Libanês',
      address: 'R. Dona Adma Jafet, 91 - São Paulo, SP',
      price: 17,
      priceHour: 17,
      priceDay: 100,
      rating: 4.6,
      reviewCount: 189,
      description: 'Estacionamento hospitalar com acesso direto ao Sírio Libanês. Ideal para consultas e procedimentos médicos.',
      features: ['Hospitalar', 'Acesso direto', 'Médico', 'Familiar', '24h'],
      imageUrl: parkingImages[11],
      rules: ['Acesso 24h', 'Desconto para pacientes', 'Valet disponível', 'Seguro hospitalar'],
      owner: {
        name: 'Sírio Libanês Adm',
        joined: 'Abril de 2019',
        responseTime: '12 min',
        rating: 4.7,
        image: parkingImages[5],
      },
      images: [parkingImages[11], parkingImages[6], parkingImages[7], parkingImages[8]],
      reviews: [
        {
          id: '32a',
          user: 'Família Carvalho',
          date: '08/04/2024',
          rating: 5,
          comment: 'Facilita muito durante internações. Equipe muito solícita.',
          image: parkingImages[9],
        },
        {
          id: '32b',
          user: 'Dr. Antonio Costa',
          date: '04/04/2024',
          rating: 4,
          comment: 'Conveniente para médicos e pacientes. Bem localizado.',
          image: parkingImages[10],
        },
      ],
      lat: -23.5631,
      lng: -46.6591,
      location: {
        lat: -23.5631,
        lng: -46.6591,
        nearbyPlaces: ['Hospital Sírio Libanês (0m)', 'Av. Paulista (100m)', 'Estação Trianon-Masp (350m)'],
      },
      availability: {
        monday: '00:00 - 23:59',
        tuesday: '00:00 - 23:59',
        wednesday: '00:00 - 23:59',
        thursday: '00:00 - 23:59',
        friday: '00:00 - 23:59',
        saturday: '00:00 - 23:59',
        sunday: '00:00 - 23:59',
      },
      type: 'Médio',
      available: true,
      distance: '280m',
    },
    '33': {
      id: '33',
      title: 'Garagem Residencial Jardins Elite',
      address: 'R. Augusta, 1508 - São Paulo, SP',
      price: 25,
      priceHour: 25,
      priceDay: 145,
      rating: 4.9,
      reviewCount: 45,
      description: 'Garagem exclusiva em edifício residencial de alto padrão nos Jardins. Vaga ampla e serviços de luxo.',
      features: ['Exclusivo', 'Alto padrão', 'Jardins', 'Luxo', 'Ampla'],
      imageUrl: parkingImages[12],
      rules: ['Apenas mensalistas', 'Cadastro prévio', 'Seguro obrigatório', 'Serviços inclusos'],
      owner: {
        name: 'Condomínio Jardins Elite',
        joined: 'Novembro de 2020',
        responseTime: '6 min',
        rating: 5.0,
        image: parkingImages[11],
      },
      images: [parkingImages[12], parkingImages[13], parkingImages[14], parkingImages[15]],
      reviews: [
        {
          id: '33a',
          user: 'Empresário Ricardo',
          date: '10/04/2024',
          rating: 5,
          comment: 'O melhor estacionamento da região. Serviço de primeira classe.',
          image: parkingImages[16],
        },
        {
          id: '33b',
          user: 'Advogada Juliana',
          date: '06/04/2024',
          rating: 5,
          comment: 'Perfeito para quem trabalha nos Jardins. Recomendo!',
          image: parkingImages[17],
        },
      ],
      lat: -23.5576,
      lng: -46.6615,
      location: {
        lat: -23.5576,
        lng: -46.6615,
        nearbyPlaces: ['Rua Oscar Freire (300m)', 'Estação Consolação (500m)', 'Shopping Cidade Jardim (800m)'],
      },
      availability: {
        monday: '06:00 - 22:00',
        tuesday: '06:00 - 22:00',
        wednesday: '06:00 - 22:00',
        thursday: '06:00 - 22:00',
        friday: '06:00 - 22:00',
        saturday: '08:00 - 20:00',
        sunday: '08:00 - 18:00',
      },
      type: 'SUV',
      available: true,
      distance: '450m',
    },
    '34': {
      id: '34',
      title: 'Estacionamento Bela Vista Business',
      address: 'R. Treze de Maio, 1947 - São Paulo, SP',
      price: 13,
      priceHour: 13,
      priceDay: 78,
      rating: 4.3,
      reviewCount: 167,
      description: 'Estacionamento comercial no coração da Bela Vista. Próximo à Paulista e com fácil acesso ao centro da cidade.',
      features: ['Comercial', 'Centro', 'Acesso fácil', 'Empresarial', 'Econômico'],
      imageUrl: parkingImages[13],
      rules: ['Horário comercial estendido', 'Desconto para empresas', 'Mensalista prioritário', 'App próprio'],
      owner: {
        name: 'Bela Vista Business Park',
        joined: 'Junho de 2021',
        responseTime: '18 min',
        rating: 4.4,
        image: parkingImages[18],
      },
      images: [parkingImages[13], parkingImages[19], parkingImages[20], parkingImages[0]],
      reviews: [
        {
          id: '34a',
          user: 'Contador Miguel',
          date: '12/04/2024',
          rating: 4,
          comment: 'Bom preço e localização conveniente. Uso frequentemente.',
          image: parkingImages[1],
        },
        {
          id: '34b',
          user: 'Consultora Sandra',
          date: '09/04/2024',
          rating: 4,
          comment: 'Estacionamento confiável para reuniões na região.',
          image: parkingImages[2],
        },
      ],
      lat: -23.5562,
      lng: -46.6523,
      location: {
        lat: -23.5562,
        lng: -46.6523,
        nearbyPlaces: ['Av. Paulista (200m)', 'Teatro Oficina (400m)', 'Estação Brigadeiro (600m)'],
      },
      availability: {
        monday: '06:00 - 21:00',
        tuesday: '06:00 - 21:00',
        wednesday: '06:00 - 21:00',
        thursday: '06:00 - 21:00',
        friday: '06:00 - 21:00',
        saturday: '08:00 - 16:00',
        sunday: 'Fechado',
      },
      type: 'Médio',
      available: true,
      distance: '350m',
    },
    '35': {
      id: '35',
      title: 'Garagem Shopping Center 3',
      address: 'Av. Paulista, 2064 - São Paulo, SP',
      price: 14,
      priceHour: 14,
      priceDay: 84,
      rating: 4.5,
      reviewCount: 298,
      description: 'Estacionamento do Shopping Center 3 na Paulista. Amplo, moderno e com desconto para compras no shopping.',
      features: ['Shopping', 'Amplo', 'Desconto compras', 'Moderno', 'Food court'],
      imageUrl: parkingImages[14],
      rules: ['Validação no shopping', 'Desconto 50% com compras', 'Máximo 5h gratuitas', 'Ticket na entrada'],
      owner: {
        name: 'Shopping Center 3',
        joined: 'Outubro de 2018',
        responseTime: '25 min',
        rating: 4.5,
        image: parkingImages[3],
      },
      images: [parkingImages[14], parkingImages[4], parkingImages[5], parkingImages[6]],
      reviews: [
        {
          id: '35a',
          user: 'Família Oliveira',
          date: '14/04/2024',
          rating: 5,
          comment: 'Perfeito para fazer compras. Sempre encontro vaga.',
          image: parkingImages[7],
        },
        {
          id: '35b',
          user: 'Estudante Carla',
          date: '11/04/2024',
          rating: 4,
          comment: 'Bom para estudar no shopping. WiFi grátis.',
          image: parkingImages[8],
        },
      ],
      lat: -23.5612,
      lng: -46.6561,
      location: {
        lat: -23.5612,
        lng: -46.6561,
        nearbyPlaces: ['Shopping Center 3 (0m)', 'MASP (100m)', 'Estação Trianon-Masp (200m)'],
      },
      availability: {
        monday: '08:00 - 22:00',
        tuesday: '08:00 - 22:00',
        wednesday: '08:00 - 22:00',
        thursday: '08:00 - 22:00',
        friday: '08:00 - 22:00',
        saturday: '08:00 - 22:00',
        sunday: '10:00 - 20:00',
      },
      type: 'Médio',
      available: true,
      distance: '150m',
    },
    '36': {
      id: '36',
      title: 'Vaga Privativa Consolação Premium',
      address: 'Av. Consolação, 3811 - São Paulo, SP',
      price: 19,
      priceHour: 19,
      priceDay: 110,
      rating: 4.7,
      reviewCount: 93,
      description: 'Garagem privativa em edifício premium na Consolação. Próximo à Paulista com acesso facilitado ao metrô.',
      features: ['Privativa', 'Premium', 'Metrô próximo', 'Elevador', 'Portaria 24h'],
      imageUrl: parkingImages[15],
      rules: ['Acesso por biometria', 'Cadastro obrigatório', 'Seguro incluso', 'Serviço de apoio'],
      owner: {
        name: 'Residencial Consolação',
        joined: 'Fevereiro de 2022',
        responseTime: '8 min',
        rating: 4.8,
        image: parkingImages[9],
      },
      images: [parkingImages[15], parkingImages[10], parkingImages[11], parkingImages[12]],
      reviews: [
        {
          id: '36a',
          user: 'Médica Fernanda',
          date: '16/04/2024',
          rating: 5,
          comment: 'Segurança excelente e localização perfeita para trabalhar na Paulista.',
          image: parkingImages[13],
        },
        {
          id: '36b',
          user: 'Engenheiro Paulo',
          date: '13/04/2024',
          rating: 4,
          comment: 'Garagem bem cuidada, mas um pouco cara para uso diário.',
          image: parkingImages[14],
        },
      ],
      lat: -23.5569,
      lng: -46.6594,
      location: {
        lat: -23.5569,
        lng: -46.6594,
        nearbyPlaces: ['Estação Consolação (200m)', 'Av. Paulista (300m)', 'Copacabana (150m)'],
      },
      availability: {
        monday: '05:00 - 23:00',
        tuesday: '05:00 - 23:00',
        wednesday: '05:00 - 23:00',
        thursday: '05:00 - 23:00',
        friday: '05:00 - 23:00',
        saturday: '06:00 - 22:00',
        sunday: '07:00 - 21:00',
      },
      type: 'Médio',
      available: true,
      distance: '380m',
    },
    '37': {
      id: '37',
      title: 'Estacionamento Banco Central Tower',
      address: 'Av. Paulista, 1776 - São Paulo, SP',
      price: 21,
      priceHour: 21,
      priceDay: 125,
      rating: 4.8,
      reviewCount: 67,
      description: 'Estacionamento corporativo em torre empresarial. Ambiente executivo com tecnologia de ponta e segurança máxima.',
      features: ['Corporativo', 'Torre', 'Tecnologia', 'Executivo', 'Segurança máxima'],
      imageUrl: parkingImages[16],
      rules: ['Acesso corporativo', 'Identificação empresarial', 'Segurança reforçada', 'Tecnologia RFID'],
      owner: {
        name: 'BC Tower Management',
        joined: 'Agosto de 2020',
        responseTime: '4 min',
        rating: 4.9,
        image: parkingImages[15],
      },
      images: [parkingImages[16], parkingImages[17], parkingImages[18], parkingImages[19]],
      reviews: [
        {
          id: '37a',
          user: 'CEO Roberto Lima',
          date: '18/04/2024',
          rating: 5,
          comment: 'Infraestrutura corporativa de primeiro mundo. Impressionante!',
          image: parkingImages[20],
        },
        {
          id: '37b',
          user: 'Diretora Ana Clara',
          date: '15/04/2024',
          rating: 5,
          comment: 'Perfeito para reuniões executivas. Recomendo sem reservas.',
          image: parkingImages[0],
        },
      ],
      lat: -23.5623,
      lng: -46.6542,
      location: {
        lat: -23.5623,
        lng: -46.6542,
        nearbyPlaces: ['Banco Central (0m)', 'Estação Trianon-Masp (300m)', 'FIESP (200m)'],
      },
      availability: {
        monday: '06:00 - 20:00',
        tuesday: '06:00 - 20:00',
        wednesday: '06:00 - 20:00',
        thursday: '06:00 - 20:00',
        friday: '06:00 - 20:00',
        saturday: '08:00 - 12:00',
        sunday: 'Fechado',
      },
      type: 'SUV',
      available: true,
      distance: '250m',
    },
    '38': {
      id: '38',
      title: 'Garagem Cultural Sesc Paulista',
      address: 'Av. Paulista, 119 - São Paulo, SP',
      price: 11,
      priceHour: 11,
      priceDay: 66,
      rating: 4.4,
      reviewCount: 178,
      description: 'Estacionamento do Sesc Paulista com desconto para associados. Ideal para atividades culturais e de lazer.',
      features: ['Cultural', 'Sesc', 'Desconto associados', 'Lazer', 'Acessível'],
      imageUrl: parkingImages[17],
      rules: ['Desconto para sócios Sesc', 'Validação em atividades', 'Horário cultural', 'Acesso para deficientes'],
      owner: {
        name: 'Sesc São Paulo',
        joined: 'Janeiro de 2019',
        responseTime: '30 min',
        rating: 4.3,
        image: parkingImages[1],
      },
      images: [parkingImages[17], parkingImages[2], parkingImages[3], parkingImages[4]],
      reviews: [
        {
          id: '38a',
          user: 'Professora Helena',
          date: '20/04/2024',
          rating: 4,
          comment: 'Preço justo e bom para atividades culturais. Sou associada há anos.',
          image: parkingImages[5],
        },
        {
          id: '38b',
          user: 'Artista João',
          date: '17/04/2024',
          rating: 5,
          comment: 'Perfeito para quem frequenta os cursos do Sesc. Recomendo!',
          image: parkingImages[6],
        },
      ],
      lat: -23.5707,
      lng: -46.6490,
      location: {
        lat: -23.5707,
        lng: -46.6490,
        nearbyPlaces: ['Sesc Paulista (0m)', 'Estação Brigadeiro (400m)', 'Parque Tenente Siqueira Campos (300m)'],
      },
      availability: {
        monday: '09:00 - 21:00',
        tuesday: '09:00 - 21:00',
        wednesday: '09:00 - 21:00',
        thursday: '09:00 - 21:00',
        friday: '09:00 - 21:00',
        saturday: '09:00 - 18:00',
        sunday: '10:00 - 17:00',
      },
      type: 'Pequeno',
      available: true,
      distance: '400m',
    },
    '39': {
      id: '39',
      title: 'Vaga Exclusiva Jardins Medical Center',
      address: 'R. Pamplona, 518 - São Paulo, SP',
      price: 18,
      priceHour: 18,
      priceDay: 105,
      rating: 4.6,
      reviewCount: 124,
      description: 'Garagem exclusiva em centro médico nos Jardins. Especializada em atendimento a pacientes e médicos.',
      features: ['Médico', 'Exclusivo', 'Jardins', 'Pacientes', 'Especializado'],
      imageUrl: parkingImages[18],
      rules: ['Prioridade pacientes', 'Desconto médicos', 'Agendamento recomendado', 'Acesso facilitado'],
      owner: {
        name: 'Jardins Medical',
        joined: 'Setembro de 2021',
        responseTime: '12 min',
        rating: 4.7,
        image: parkingImages[7],
      },
      images: [parkingImages[18], parkingImages[8], parkingImages[9], parkingImages[10]],
      reviews: [
        {
          id: '39a',
          user: 'Paciente Maria José',
          date: '22/04/2024',
          rating: 5,
          comment: 'Atendimento humanizado e vaga sempre disponível para consultas.',
          image: parkingImages[11],
        },
        {
          id: '39b',
          user: 'Dr. Carlos Mendes',
          date: '19/04/2024',
          rating: 4,
          comment: 'Conveniente para médicos. Localização excelente nos Jardins.',
          image: parkingImages[12],
        },
      ],
      lat: -23.5651,
      lng: -46.6611,
      location: {
        lat: -23.5651,
        lng: -46.6611,
        nearbyPlaces: ['Jardins Medical Center (0m)', 'Rua Oscar Freire (200m)', 'Estação Consolação (500m)'],
      },
      availability: {
        monday: '06:00 - 20:00',
        tuesday: '06:00 - 20:00',
        wednesday: '06:00 - 20:00',
        thursday: '06:00 - 20:00',
        friday: '06:00 - 20:00',
        saturday: '08:00 - 14:00',
        sunday: 'Apenas emergências',
      },
      type: 'Médio',
      available: true,
      distance: '480m',
    },
    '40': {
      id: '40',
      title: 'Estacionamento Paulista Innovation Hub',
      address: 'Av. Paulista, 2300 - São Paulo, SP',
      price: 16,
      priceHour: 16,
      priceDay: 95,
      rating: 4.7,
      reviewCount: 156,
      description: 'Estacionamento moderno em hub de inovação. Ambiente tech com carregadores elétricos e espaços colaborativos.',
      features: ['Innovation', 'Tech', 'Carregadores EV', 'Colaborativo', 'Moderno'],
      imageUrl: parkingImages[19],
      rules: ['Carregamento EV gratuito', 'Coworking disponível', 'WiFi liberado', 'Eventos tech'],
      owner: {
        name: 'Innovation Hub SP',
        joined: 'Maio de 2023',
        responseTime: '7 min',
        rating: 4.8,
        image: parkingImages[13],
      },
      images: [parkingImages[19], parkingImages[14], parkingImages[15], parkingImages[16]],
      reviews: [
        {
          id: '40a',
          user: 'Startup CEO Lucas',
          date: '24/04/2024',
          rating: 5,
          comment: 'Perfeito para empreendedores! Ambiente inspirador e networking.',
          image: parkingImages[17],
        },
        {
          id: '40b',
          user: 'Developer Ana Tech',
          date: '21/04/2024',
          rating: 5,
          comment: 'Amo trabalhar aqui! Carregador EV é um diferencial incrível.',
          image: parkingImages[18],
        },
      ],
      lat: -23.5590,
      lng: -46.6502,
      location: {
        lat: -23.5590,
        lng: -46.6502,
        nearbyPlaces: ['Innovation Hub (0m)', 'Estação Consolação (300m)', 'Casa das Rosas (400m)'],
      },
      availability: {
        monday: '07:00 - 23:00',
        tuesday: '07:00 - 23:00',
        wednesday: '07:00 - 23:00',
        thursday: '07:00 - 23:00',
        friday: '07:00 - 23:00',
        saturday: '09:00 - 19:00',
        sunday: '10:00 - 18:00',
      },
      type: 'Médio',
      available: true,
      distance: '350m',
    },
  };
  
  const space = mockSpaces[id];
  
  if (!space) {
    console.log('❌ Vaga não encontrada nem no Supabase nem nos dados mock para ID:', id);
    throw new Error(`Vaga ${id} não encontrada`);
  }
  
  console.log('✅ Vaga encontrada nos dados mock:', space);
  return space;
}

// Nova função para buscar vagas por proximidade integrada com Supabase
export async function fetchSpaces(lat: number, lng: number, radius: number = 10): Promise<SpaceProps[]> {
  console.log(`Buscando vagas próximas a ${lat}, ${lng} em um raio de ${radius}km`);
  
  let allSpaces: SpaceProps[] = [];
  
  try {
    // Buscar vagas do Supabase - APENAS VAGAS DISPONÍVEIS
    const { data: vagasFromDB, error } = await supabase
      .from('vagas')
      .select('*')
      .eq('available', true)
      .not('lat', 'is', null)
      .not('lng', 'is', null)
      .not('preco_hora', 'is', null);
    
    if (error) {
      console.error('Erro ao buscar vagas do Supabase:', error);
      throw error;
    }
    
    console.log(`Encontradas ${vagasFromDB?.length || 0} vagas no banco de dados`);
    
    // Cleanup: remover imagens externas indesejadas do DB (unsplash/pexels/picsum)
    try {
      await supabase
        .from('vagas')
        .update({ image_url: null })
        .or('image_url.ilike.%images.unsplash.com%,image_url.ilike.%unsplash.com%,image_url.ilike.%pexels.com%,image_url.ilike.%picsum.photos%');
    } catch (cleanupErr) {
      console.warn('Falha ao limpar imagens externas do DB (ignorado):', cleanupErr);
    }
    
    // Converter vagas do banco para o formato SpaceProps
    const spacesFromDB: SpaceProps[] = (vagasFromDB || []).map(vaga => ({
      id: vaga.id,
      title: vaga.titulo,
      address: vaga.endereco || `${vaga.bairro}, ${vaga.cidade}`,
      price: Number(vaga.price) || Number(vaga.preco_hora) || 10,
      rating: Number(vaga.rating) || 4.0,
      reviewCount: Math.floor(Math.random() * 200) + 20,
      imageUrl: (vaga.image_url && !vaga.image_url.includes('unsplash.com') && !vaga.image_url.includes('images.unsplash.com') && !vaga.image_url.includes('pexels.com') && !vaga.image_url.includes('picsum.photos') && !vaga.image_url.includes('placeholder') ? vaga.image_url : parkingImages[0]),
      features: vaga.features || vaga.recursos || ['Básico'],
      available: vaga.available === true,
      lat: Number(vaga.lat),
      lng: Number(vaga.lng),
      type: 'Médio' as const,
      distance: '0km',
      discount_premium: vaga.discount_premium || false
    }));
    
    // Vagas mocadas originais (fallback)
    const mockSpaces: SpaceProps[] = [
      {
        id: 'mock1',
        title: 'Estacionamento Seguro na Paulista',
        address: 'Av. Paulista, 1000 - São Paulo',
        price: 15,
        rating: 4.8,
        reviewCount: 125,
        imageUrl: parkingImages[0],
        features: ['Coberto', 'Segurança 24h', 'Carregador EV'],
        available: true,
        lat: -23.5613,
        lng: -46.6558,
        type: 'Médio',
        distance: '0km'
      },
      {
        id: 'mock2',
        title: 'Vaga Residencial em Pinheiros',
        address: 'R. dos Pinheiros, 275 - São Paulo',
        price: 10,
        rating: 4.5,
        reviewCount: 87,
        imageUrl: parkingImages[1],
        images: [
          parkingImages[1],
          parkingImages[2],
          parkingImages[3],
          parkingImages[4],
          parkingImages[5],
        ],
        features: ['Privativo', 'Coberto'],
        available: true,
        lat: -23.5651,
        lng: -46.6911,
        type: 'Pequeno',
        distance: '0km'
      }
    ];
    
    // Função para gerar vagas em cluster
    const generateCluster = (
      prefix: string,
      name: string,
      city: string,
      baseLat: number,
      baseLng: number,
      count: number
    ): SpaceProps[] => {
      const types: SpaceProps['type'][] = ['Pequeno', 'Médio', 'SUV'];
      const imgs = getRandomParkingImages(5);
      const feats = [
        ['Coberto', 'Segurança 24h'],
        ['Residencial', 'Privativo'],
        ['WIFI', 'Coberto'],
        ['Próximo ao comércio'],
        ['Carregador EV', 'Monitoramento'],
        ['Iluminado', 'Acesso fácil']
      ];
      return Array.from({ length: count }).map((_, i) => {
        const jitterLat = (Math.random() - 0.5) * 0.02; // ~2km
        const jitterLng = (Math.random() - 0.5) * 0.02;
        const price = 5 + Math.floor(Math.random() * 16); // 5-20
        return {
          id: `${prefix}-${String(i + 1).padStart(3, '0')}`,
          title: `Vaga ${name} #${i + 1}`,
          address: `${name}, ${city} - SP`,
          price,
          rating: +(3.8 + Math.random() * 1.2).toFixed(1),
          reviewCount: 20 + Math.floor(Math.random() * 180),
          imageUrl: imgs[0],
          images: imgs,
          features: feats[i % feats.length],
          available: true,
          lat: +(baseLat + jitterLat).toFixed(6),
          lng: +(baseLng + jitterLng).toFixed(6),
          type: types[i % types.length],
          distance: '0km'
        };
      });
    };

    // Adicionar vagas extras para as regiões solicitadas
    const extraSpaces: SpaceProps[] = [
      // Mogi das Cruzes – Centro
      ...generateCluster('mogi-centro', 'Centro', 'Mogi das Cruzes', -23.5224, -46.1857, 30),
      // Mogi das Cruzes – Vila Mogilar  
      ...generateCluster('mogi-mogilar', 'Vila Mogilar', 'Mogi das Cruzes', -23.5334, -46.1864, 20),
      // Mogi das Cruzes – Parque Centenário
      ...generateCluster('mogi-parque-centenario', 'Parque Centenário', 'Mogi das Cruzes', -23.5195, -46.1812, 30),
      // Mogi das Cruzes – Supermercado Alabarce (região)
      ...generateCluster('mogi-alabarce', 'Alabarce', 'Mogi das Cruzes', -23.5360, -46.1827, 20),
      // Ferraz de Vasconcelos – Rua Serrana 380 (região)
      ...generateCluster('ferraz-rua-serrana', 'Rua Serrana', 'Ferraz de Vasconcelos', -23.5407, -46.3692, 25)
    ];
    
    // Mesclar todas as vagas: banco + mockadas + extras
    allSpaces = [...spacesFromDB, ...mockSpaces, ...extraSpaces];
    console.log(`Total de vagas disponíveis: ${allSpaces.length}`);
    
  } catch (error) {
    console.error('Erro ao buscar vagas:', error);
    // Em caso de erro, usar apenas dados mocados como fallback
    allSpaces = [
      {
        id: 'fallback1',
        title: 'Vaga Fallback - Centro SP',
        address: 'Centro, São Paulo - SP',
        price: 10,
        rating: 4.0,
        reviewCount: 50,
        imageUrl: parkingImages[0],
        features: ['Básico'],
        available: true,
        lat: -23.5505,
        lng: -46.6333,
        type: 'Médio',
        distance: '0km'
      }
    ];
  }
  
  // Simular delay da API
  await new Promise(resolve => setTimeout(resolve, 400));
  
  // Calcular distância para cada vaga e filtrar por raio
  const spacesWithDistance = allSpaces
    .filter(space => space.lat && space.lng) // Garantir que tem coordenadas
    .map(space => {
      const distance = calculateDistance(lat, lng, space.lat!, space.lng!);
      return {
        ...space,
        distance: formatDistance(distance),
        distanceKm: distance
      };
    })
    .filter(space => space.distanceKm <= radius) // Filtrar por raio
    .sort((a, b) => a.distanceKm - b.distanceKm); // Ordenar por proximidade
  
  console.log(`Encontradas ${spacesWithDistance.length} vagas em um raio de ${radius}km`);
  
  return spacesWithDistance;
}
