-- Inserir 10 novas vagas na Av. Paulista e região
INSERT INTO vagas (
  titulo, 
  endereco, 
  bairro, 
  cidade, 
  lat, 
  lng, 
  price, 
  preco_hora, 
  preco_dia, 
  preco_mes, 
  recursos, 
  features, 
  available, 
  discount_premium,
  rating,
  image_url,
  disponibilidade
) VALUES 
-- Vaga 1: Shopping Center 3
(
  'Garagem Coberta - Shopping Center 3',
  'Rua Augusta, 2690 - Cerqueira César',
  'Cerqueira César',
  'São Paulo',
  -23.5597,
  -46.6554,
  25.00,
  25.00,
  200.00,
  4500.00,
  ARRAY['Coberto', 'Segurança 24h', 'Lavagem'],
  ARRAY['Coberto', 'Segurança 24h', 'Lavagem'],
  true,
  true,
  4.6,
  '/src/assets/parking/shopping-garage-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 2: Edifício Copacabana
(
  'Vaga Premium - Edifício Copacabana',
  'Avenida Paulista, 1374 - Bela Vista',
  'Bela Vista', 
  'São Paulo',
  -23.5615,
  -46.6563,
  35.00,
  35.00,
  280.00,
  6300.00,
  ARRAY['Privativo', 'Segurança', 'Carregador EV'],
  ARRAY['Privativo', 'Segurança', 'Carregador EV'],
  true,
  true,
  4.8,
  '/src/assets/parking/premium-ev-garage-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 3: Conjunto Nacional
(
  'Garagem Subterrânea - Conjunto Nacional',
  'Avenida Paulista, 2073 - Consolação',
  'Consolação',
  'São Paulo', 
  -23.5585,
  -46.6550,
  28.00,
  28.00,
  224.00,
  5040.00,
  ARRAY['Coberto', 'Segurança 24h'],
  ARRAY['Coberto', 'Segurança 24h'],
  true,
  false,
  4.4,
  '/src/assets/parking/underground-garage-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 4: Rua Oscar Freire
(
  'Garagem Moderna - Oscar Freire',
  'Rua Oscar Freire, 379 - Jardins',
  'Jardins',
  'São Paulo',
  -23.5647,
  -46.6704,
  40.00,
  40.00,
  320.00,
  7200.00,
  ARRAY['Privativo', 'Segurança', 'Carregador EV', 'Lavagem'],
  ARRAY['Privativo', 'Segurança', 'Carregador EV', 'Lavagem'],
  true,
  true,
  4.9,
  '/src/assets/parking/modern-garage-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 5: Alameda Santos
(
  'Estacionamento Coberto - Alameda Santos',
  'Alameda Santos, 2326 - Jardins',
  'Jardins',
  'São Paulo',
  -23.5656,
  -46.6625,
  22.00,
  22.00,
  176.00,
  3960.00,
  ARRAY['Coberto', 'Segurança'],
  ARRAY['Coberto', 'Segurança'],
  true,
  false,
  4.2,
  '/src/assets/parking/covered-parking-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 6: Rua Haddock Lobo
(
  'Garagem Residencial - Haddock Lobo',
  'Rua Haddock Lobo, 595 - Cerqueira César',
  'Cerqueira César',
  'São Paulo',
  -23.5634,
  -46.6598,
  18.00,
  18.00,
  144.00,
  3240.00,
  ARRAY['Privativo', '24h'],
  ARRAY['Privativo', '24h'],
  true,
  false,
  4.1,
  '/src/assets/parking/garage-empty-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 7: Rua da Consolação
(
  'Estacionamento EV - Consolação',
  'Rua da Consolação, 3811 - Jardins',
  'Jardins',
  'São Paulo',
  -23.5569,
  -46.6594,
  32.00,
  32.00,
  256.00,
  5760.00,
  ARRAY['Carregador EV', 'Coberto', 'Segurança 24h'],
  ARRAY['Carregador EV', 'Coberto', 'Segurança 24h'],
  true,
  true,
  4.7,
  '/src/assets/parking/garage-ev-charger-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 8: Avenida Brigadeiro Luís Antônio
(
  'Garagem Compacta - Brig. Luís Antônio',
  'Avenida Brigadeiro Luís Antônio, 2344 - Bela Vista',
  'Bela Vista',
  'São Paulo',
  -23.5632,
  -46.6513,
  20.00,
  20.00,
  160.00,
  3600.00,
  ARRAY['Coberto', 'Segurança'],
  ARRAY['Coberto', 'Segurança'],
  true,
  false,
  4.0,
  '/src/assets/parking/compact-urban-1.jpg',
  '{"24h": false, "seg_sex": {"inicio": "07:00", "fim": "19:00"}, "sabado": {"inicio": "08:00", "fim": "14:00"}}'::jsonb
),
-- Vaga 9: Rua Estados Unidos
(
  'Estacionamento Descoberto - Estados Unidos',
  'Rua Estados Unidos, 1645 - Jardins',
  'Jardins',
  'São Paulo',
  -23.5711,
  -46.6672,
  15.00,
  15.00,
  120.00,
  2700.00,
  ARRAY['Segurança', '24h'],
  ARRAY['Segurança', '24h'],
  true,
  false,
  3.8,
  '/src/assets/parking/outdoor-covered-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
),
-- Vaga 10: Alameda Ribeiro da Silva
(
  'Garagem Luxo - Alameda Ribeiro',
  'Alameda Ribeiro da Silva, 115 - Bela Vista',
  'Bela Vista',
  'São Paulo',
  -23.5601,
  -46.6489,
  45.00,
  45.00,
  360.00,
  8100.00,
  ARRAY['Privativo', 'Carregador EV', 'Segurança 24h', 'Lavagem'],
  ARRAY['Privativo', 'Carregador EV', 'Segurança 24h', 'Lavagem'],
  true,
  true,
  4.9,
  '/src/assets/parking/garage-with-car-1.jpg',
  '{"24h": true, "feriados": true, "fins_semana": true}'::jsonb
);