// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axtopbwmwmajrrujqoza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dG9wYndtd21hanJydWpxb3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzM5MDMsImV4cCI6MjA2NDA0OTkwM30.x4FIBMNz7Z6u3a1yS7m8RkubGS0Q3SaYKDgHdJ67oRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);